// ============================
// STYLES (Centralized)
// ============================
const styles = {
  header: {
    background: 'linear-gradient(135deg, var(--bg-secondary) 0%, var(--bg-card) 100%)',
    borderBottom: '1px solid var(--border)',
    padding: '16px 28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  logoArea: { display: 'flex', alignItems: 'center', gap: 12 },
  logoIcon: {
    width: 40,
    height: 40,
    background: 'linear-gradient(135deg, var(--accent), #06b6a0)',
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 18,
    fontWeight: 700,
    color: 'var(--bg-primary)',
    boxShadow: '0 4px 16px rgba(13,223,186,0.3)',
  },
  logoText: { fontSize: 19, fontWeight: 700, letterSpacing: -0.5 },
  statsArea: { display: 'flex', gap: 16, alignItems: 'center' },
  statBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '5px 12px',
    background: 'var(--bg-primary)',
    borderRadius: 18,
    border: '1px solid var(--border)',
  },
  statDot: { width: 8, height: 8, borderRadius: '50%' },

  // Mobile menu toggle
  mobileMenuBtn: {
    display: 'none',
    width: 38,
    height: 38,
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'var(--bg-card)',
    color: 'var(--text-primary)',
    cursor: 'pointer',
    fontSize: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },

  main: { display: 'flex', height: 'calc(100vh - 73px)', position: 'relative' },

  // Sidebar overlay for mobile
  sidebarOverlay: {
    display: 'none',
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0,0,0,0.5)',
    zIndex: 149,
  },
  sidebarOverlayVisible: {
    display: 'block',
  },

  sidebar: {
    width: 400,
    minWidth: 400,
    background: 'var(--bg-secondary)',
    borderRight: '1px solid var(--border)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    transition: 'transform 0.3s ease',
    zIndex: 150,
  },
  urlInputArea: { flex: 1, overflow: 'hidden', display: 'flex', flexDirection: 'column', padding: 20 },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    color: 'var(--text-muted)',
    marginBottom: 12,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  urlCount: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    color: 'var(--text-muted)',
    padding: '2px 8px',
    background: 'var(--bg-primary)',
    borderRadius: 6,
  },
  textarea: {
    flex: 1,
    width: '100%',
    background: 'var(--bg-primary)',
    border: '1px solid var(--border)',
    borderRadius: 10,
    color: 'var(--text-primary)',
    fontFamily: "'Space Mono', monospace",
    fontSize: 12,
    lineHeight: 1.8,
    padding: 14,
    resize: 'none',
    outline: 'none',
  },
  textareaDragOver: {
    borderColor: 'var(--accent)',
    boxShadow: '0 0 12px rgba(13,223,186,0.3)',
    background: 'rgba(13,223,186,0.05)',
  },
  dragOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 10,
    background: 'rgba(13,223,186,0.08)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'none',
    color: 'var(--accent)',
    fontSize: 13,
    fontWeight: 600,
    border: '2px dashed var(--accent)',
  },
  queueSection: {
    maxHeight: 200,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    borderTop: '1px solid var(--border)',
  },
  queueList: { flex: 1, overflowY: 'auto' },
  queueItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '8px 20px',
    borderBottom: '1px solid var(--border)',
    fontSize: 12,
  },
  queueUrl: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    flex: 1,
  },
  progressSection: {
    padding: '14px 20px',
    borderTop: '1px solid var(--border)',
  },
  progressInfo: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: 8,
    fontSize: 12,
    color: 'var(--text-secondary)',
  },
  progressTrack: {
    height: 6,
    background: 'var(--bg-primary)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: 'linear-gradient(90deg, var(--accent), #06e8c0)',
    borderRadius: 3,
    transition: 'width 0.5s ease',
  },
  sidebarActions: {
    padding: '14px 20px',
    display: 'flex',
    gap: 10,
    borderTop: '1px solid var(--border)',
    background: 'var(--bg-secondary)',
    flexWrap: 'wrap',
  },
  concurrencySelector: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    width: '100%',
    marginBottom: 4,
    fontSize: 12,
    color: 'var(--text-muted)',
  },
  concurrencySelect: {
    background: 'var(--bg-primary)',
    border: '1px solid var(--border)',
    borderRadius: 6,
    color: 'var(--text-primary)',
    fontSize: 12,
    padding: '4px 8px',
    outline: 'none',
    fontFamily: "'DM Sans', sans-serif",
  },

  btn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: '11px 22px',
    borderRadius: 8,
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 14,
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'all 0.2s',
  },
  btnPrimary: {
    background: 'linear-gradient(135deg, var(--accent), #06b6a0)',
    color: 'var(--bg-primary)',
    boxShadow: '0 4px 16px rgba(13,223,186,0.25)',
  },
  btnSecondary: {
    background: 'var(--bg-card)',
    color: 'var(--text-primary)',
    border: '1px solid var(--border)',
  },
  btnDanger: {
    background: 'rgba(239,68,68,0.15)',
    color: 'var(--danger)',
    border: '1px solid rgba(239,68,68,0.3)',
  },
  btnExport: {
    background: 'linear-gradient(135deg, var(--accent-orange), #e55a2b)',
    color: 'white',
    boxShadow: '0 4px 16px rgba(255,107,53,0.25)',
  },
  btnSmall: {
    padding: '6px 12px',
    fontSize: 12,
  },
  btnRetry: {
    background: 'rgba(245,158,11,0.15)',
    color: 'var(--warning)',
    border: '1px solid rgba(245,158,11,0.3)',
  },

  content: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  toolbar: {
    padding: '12px 24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid var(--border)',
    background: 'var(--bg-secondary)',
    flexShrink: 0,
    flexWrap: 'wrap',
    gap: 8,
  },
  toolbarLeft: { display: 'flex', alignItems: 'center', gap: 16, flexWrap: 'wrap' },
  toolbarRight: { display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' },
  tabGroup: {
    display: 'flex',
    background: 'var(--bg-primary)',
    borderRadius: 8,
    padding: 3,
    border: '1px solid var(--border)',
  },
  tab: {
    padding: '7px 16px',
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
    color: 'var(--text-secondary)',
    border: 'none',
    background: 'transparent',
    fontFamily: "'DM Sans', sans-serif",
    transition: 'all 0.2s',
  },
  tabActive: {
    background: 'var(--accent)',
    color: 'var(--bg-primary)',
    fontWeight: 600,
  },

  // Search & filters
  searchInput: {
    background: 'var(--bg-primary)',
    border: '1px solid var(--border)',
    borderRadius: 6,
    color: 'var(--text-primary)',
    fontSize: 13,
    padding: '7px 12px',
    outline: 'none',
    fontFamily: "'DM Sans', sans-serif",
    width: 180,
    transition: 'border-color 0.2s',
  },
  filterSelect: {
    background: 'var(--bg-primary)',
    border: '1px solid var(--border)',
    borderRadius: 6,
    color: 'var(--text-primary)',
    fontSize: 12,
    padding: '7px 10px',
    outline: 'none',
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
  },

  resultsContainer: { flex: 1, overflow: 'auto', padding: 20 },

  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    gap: 14,
    color: 'var(--text-muted)',
  },
  emptyIcon: {
    width: 80,
    height: 80,
    background: 'var(--bg-card)',
    borderRadius: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 36,
    border: '1px dashed var(--border)',
  },

  cardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))',
    gap: 18,
  },
  card: {
    background: 'var(--bg-card)',
    border: '1px solid var(--border)',
    borderRadius: 12,
    overflow: 'hidden',
    cursor: 'pointer',
    transition: 'all 0.25s',
  },
  cardBanner: {
    height: 110,
    position: 'relative',
  },
  cardCategory: {
    position: 'absolute',
    top: 10,
    right: 10,
    padding: '4px 10px',
    background: 'rgba(0,0,0,0.65)',
    backdropFilter: 'blur(8px)',
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--accent)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  cardCacheBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    padding: '3px 8px',
    background: 'rgba(245,158,11,0.8)',
    borderRadius: 6,
    fontSize: 10,
    fontWeight: 600,
    color: '#fff',
  },
  cardBody: { padding: '14px 18px' },
  cardTitle: { fontSize: 15, fontWeight: 700, marginBottom: 8, lineHeight: 1.3 },
  cardMeta: { display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 10 },
  metaTag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    fontSize: 12,
    color: 'var(--text-muted)',
    background: 'var(--bg-primary)',
    padding: '3px 10px',
    borderRadius: 6,
  },
  cardCities: { fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.5 },
  cardFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 18px',
    borderTop: '1px solid var(--border)',
    background: 'rgba(0,0,0,0.12)',
  },
  cardStatus: { display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, fontWeight: 500 },
  detailBtn: {
    width: 30,
    height: 30,
    borderRadius: 6,
    border: '1px solid var(--border)',
    background: 'var(--bg-card)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
  },

  table: { width: '100%', borderCollapse: 'separate', borderSpacing: 0, fontSize: 13 },
  th: {
    background: 'var(--bg-card)',
    padding: '10px 14px',
    textAlign: 'left',
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: 'var(--text-muted)',
    borderBottom: '2px solid var(--accent)',
    whiteSpace: 'nowrap',
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  td: {
    padding: '10px 14px',
    borderBottom: '1px solid var(--border)',
    maxWidth: 220,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: 'var(--text-secondary)',
  },

  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0,0,0,0.6)',
    backdropFilter: 'blur(4px)',
    zIndex: 200,
    display: 'flex',
    justifyContent: 'flex-end',
  },
  detailPanel: {
    width: 700,
    maxWidth: '92vw',
    background: 'var(--bg-secondary)',
    borderLeft: '1px solid var(--border)',
    overflowY: 'auto',
  },
  detailHeader: {
    padding: '20px 24px',
    borderBottom: '1px solid var(--border)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'sticky',
    top: 0,
    background: 'var(--bg-secondary)',
    zIndex: 10,
  },
  closeBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'var(--bg-card)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    fontSize: 16,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailBody: { padding: '20px 24px' },

  editableInput: {
    flex: 1,
    background: 'var(--bg-primary)',
    border: '1px solid var(--border)',
    borderRadius: 6,
    color: 'var(--text-primary)',
    fontSize: 13,
    padding: '5px 10px',
    fontFamily: "'DM Sans', sans-serif",
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  editableTextarea: {
    width: '100%',
    background: 'var(--bg-primary)',
    border: '1px solid var(--border)',
    borderRadius: 6,
    color: 'var(--text-primary)',
    fontSize: 13,
    padding: '8px 10px',
    fontFamily: "'DM Sans', sans-serif",
    resize: 'vertical',
    minHeight: 70,
    outline: 'none',
    lineHeight: 1.5,
    transition: 'border-color 0.2s',
    boxSizing: 'border-box',
  },
};

export default styles;
