export const COUNTRY_ALIASES = {
  eeuu: 'Estados Unidos',
  'ee.uu': 'Estados Unidos',
  'ee. uu': 'Estados Unidos',
  usa: 'Estados Unidos',
  'u.s.a': 'Estados Unidos',
  'estados unidos de america': 'Estados Unidos',
  rep_checa: 'República Checa',
  republica_checa: 'República Checa',
  chequia: 'República Checa',
  czech_republic: 'República Checa',
  reino_unido: 'Reino Unido',
  uk: 'Reino Unido',
};

export const CAPITAL_TO_COUNTRY = {
  madrid: 'España',
  paris: 'Francia',
  lisboa: 'Portugal',
  roma: 'Italia',
  berlin: 'Alemania',
  viena: 'Austria',
  bruselas: 'Bélgica',
  amsterdam: 'Países Bajos',
  praga: 'Chequia',
  budapest: 'Hungría',
  atenas: 'Grecia',
  londres: 'Reino Unido',
  dublin: 'Irlanda',
  oslo: 'Noruega',
  estocolmo: 'Suecia',
  copenhague: 'Dinamarca',
  helsinki: 'Finlandia',
  varsovia: 'Polonia',
  zurich: 'Suiza',
  sofia: 'Bulgaria',
  bucarest: 'Rumanía',
  estambul: 'Turquía',
  ankara: 'Turquía',
  tokio: 'Japón',
  seul: 'Corea del Sur',
  pekin: 'China',
  beijing: 'China',
  bangkok: 'Tailandia',
  hanoi: 'Vietnam',
  delhi: 'India',
  nueva_delhi: 'India',
  cairo: 'Egipto',
  rabat: 'Marruecos',
  tunez: 'Túnez',
  washington: 'Estados Unidos',
  washington_dc: 'Estados Unidos',
  ottawa: 'Canadá',
  ciudad_de_mexico: 'México',
  bogota: 'Colombia',
  lima: 'Perú',
  santiago: 'Chile',
  buenos_aires: 'Argentina',
  montevideo: 'Uruguay',
  asuncion: 'Paraguay',
  quito: 'Ecuador',
  la_paz: 'Bolivia',
};

export const SPAIN_AUTONOMOUS_COMMUNITIES = [
  'Andalucía',
  'Aragón',
  'Asturias',
  'Illes Balears',
  'Canarias',
  'Cantabria',
  'Castilla-La Mancha',
  'Castilla y León',
  'Cataluña',
  'Comunidad de Madrid',
  'Comunidad Foral de Navarra',
  'Comunitat Valenciana',
  'Extremadura',
  'Galicia',
  'La Rioja',
  'País Vasco',
  'Región de Murcia',
];

export const SPAIN_CITY_TO_REGION = {
  madrid: 'Comunidad de Madrid',
  barcelona: 'Cataluña',
  sevilla: 'Andalucía',
  malaga: 'Andalucía',
  granada: 'Andalucía',
  cordoba: 'Andalucía',
  cadiz: 'Andalucía',
  valencia: 'Comunitat Valenciana',
  alicante: 'Comunitat Valenciana',
  castellon: 'Comunitat Valenciana',
  bilbao: 'País Vasco',
  san_sebastian: 'País Vasco',
  vitoria: 'País Vasco',
  santiago_de_compostela: 'Galicia',
  a_coruna: 'Galicia',
  vigo: 'Galicia',
  murcia: 'Región de Murcia',
  pamplona: 'Comunidad Foral de Navarra',
  zaragoza: 'Aragón',
  valladolid: 'Castilla y León',
  salamanca: 'Castilla y León',
  leon: 'Castilla y León',
  toledo: 'Castilla-La Mancha',
  cuenca: 'Castilla-La Mancha',
  albacete: 'Castilla-La Mancha',
  santander: 'Cantabria',
  logrono: 'La Rioja',
  oviedo: 'Asturias',
  gijon: 'Asturias',
  merida: 'Extremadura',
  badajoz: 'Extremadura',
  caceres: 'Extremadura',
  palma: 'Illes Balears',
  ibiza: 'Illes Balears',
  mahon: 'Illes Balears',
  las_palmas: 'Canarias',
  santa_cruz_de_tenerife: 'Canarias',
};
